version: '3'

volumes:
  redis_data:
    external: false 

services:

  redis:
    image: redis:latest
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  fastapi:
    build: ./fastapi/
    container_name: fastapi
    depends_on:
      redis:
        condition: service_healthy
  
  nginx:
    build: ./nginx/
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - fastapi
